---
abstract: 'Remote-control Win32 GUI applications'
author:
  - 'Toby Ovod-Everett <toby@ovod-everett.org>'
  - 'Christopher J. Madsen <perl@cjmweb.net>'
build_requires:
  Module::Build: 0.25
  Test::More: 0
configure_requires:
  Module::Build: 0.25
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Win32-CtrlGUI
requires:
  Win32::Setupsup: 0
  overload: 0
  perl: 5.006
  vars: 0
resources:
  repository: git://github.com/madsen/win32-ctrlgui.git
version: 0.31
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: Git::NextVersion
      version: 2.000
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: 0.004000
    -
      class: Dist::Zilla::Plugin::FileFinder::ByName
      name: ':BuildPL'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: ':FilesWithPod'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: ':FilesForAutoPrereqs'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: CJM/GatherDir
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: CJM/PruneCruft
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: CJM/ManifestSkip
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: CJM/MetaJSON
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: CJM/MetaYAML
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::License
      name: CJM/License
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::Test::PrereqsFromMeta
      name: CJM/Test::PrereqsFromMeta
      version: 4.04
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: CJM/PodSyntaxTests
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: CJM/PodCoverageTests
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: CJM/ExtraTests
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::PodLoom
      config:
        Pod::Loom version: 0.05
      name: CJM/PodLoom
      version: 4.10
    -
      class: Dist::Zilla::Plugin::ModuleBuild::Custom
      name: CJM/ModuleBuild::Custom
      version: 4.07
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: CJM/MetaConfig
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::MatchManifest
      name: CJM/MatchManifest
      version: 4.00
    -
      class: Dist::Zilla::Plugin::RecommendedPrereqs
      name: CJM/RecommendedPrereqs
      version: 4.06
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CJM/CheckPrereqsIndexed
      version: 0.006
    -
      class: Dist::Zilla::Plugin::GitVersionCheckCJM
      name: CJM/GitVersionCheckCJM
      version: 4.03
    -
      class: Dist::Zilla::Plugin::TemplateCJM
      name: CJM/TemplateCJM
      version: 4.00
    -
      class: Dist::Zilla::Plugin::Repository
      name: CJM/Repository
      version: 0.16
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: CJM/@Git/Check
      version: 2.000
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: CJM/@Git/Commit
      version: 2.000
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: CJM/@Git/Tag
      version: 2.000
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: CJM/@Git/Push
      version: 2.000
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: CJM/TestRelease
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: CJM/UploadToCPAN
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: CJM/ArchiveRelease
      version: 4.00
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300024
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300024
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300024
